# Generated by Django 3.0.2 on 2020-01-05 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_search', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlimentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fresh', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('nb_people', models.SmallIntegerField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('nb_people', models.SmallIntegerField(blank=True, default=1)),
                ('stars', models.SmallIntegerField(blank=True, choices=[(1, 'very bad'), (2, 'bad'), (3, 'mediocre'), (4, 'good'), (5, 'very good')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ReceipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta)),
                ('receipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rawfood.Receipe')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlimentNutrition',
            fields=[
                ('protein', models.PositiveIntegerField()),
                ('glucid', models.PositiveIntegerField()),
                ('lipid', models.PositiveIntegerField()),
                ('aliment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rawfood.Aliment')),
            ],
        ),
        migrations.CreateModel(
            name='ReceipeStepReceipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawfood.Receipe')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipe_ingredients', to='rawfood.ReceipeStep')),
            ],
        ),
        migrations.CreateModel(
            name='ReceipeStepAliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit', models.SmallIntegerField(choices=[(1, 'g'), (2, 'unit')])),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawfood.Aliment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliment_ingredients', to='rawfood.ReceipeStep')),
            ],
        ),
        migrations.AddField(
            model_name='receipe',
            name='utensils',
            field=models.ManyToManyField(blank=True, related_name='receipes', to='rawfood.Utensil'),
        ),
        migrations.CreateModel(
            name='MealReceipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipes', to='rawfood.Meal')),
                ('receipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawfood.Receipe')),
            ],
        ),
        migrations.CreateModel(
            name='MealAliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit', models.SmallIntegerField(choices=[(1, 'g'), (2, 'unit')])),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawfood.Aliment')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliments', to='rawfood.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='aliment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliments', to='rawfood.AlimentCategory'),
        ),
    ]
